### ISSUE TITLE
Human annotation data

### ISSUE THREAD

**Issue by SherryXTChen** [cocoshe/I2EBench#1]
Thank you for releasing the dataset. I am having a hard time find the human annotation data though. Would you please direct me to where it is? Thank you!

**Comment by cocoshe** [comment]
> Thank you for releasing the dataset. I am having a hard time find the human annotation data though. Would you please direct me to where it is? Thank you!

Thanks for your interest to our work, the human annotation data can be find [here](https://github.com/cocoshe/I2EBench/blob/main/EditData/BGReplacement/BGReplacement.json), they are all in `EditData` folder. The `BGReplacement` indicates the specific task, and the jsons like [BGReplacement.json](https://github.com/cocoshe/I2EBench/blob/main/EditData/BGReplacement/BGReplacement.json), [BGReplacement_2nd.json](https://github.com/cocoshe/I2EBench/blob/main/EditData/BGReplacement/BGReplacement_2nd.json) indicate the editing instructions for each editing round.

**Comment by SherryXTChen** [comment]
Got it. Thank you!
